### PR TITLE
fixing the cringe label

### PR DESCRIPTION
**Pull request by tekakutli**
some code cleaned up
the rest is to make it easy for users, no need to configure the bash file

### CODE REVIEW

**Comment by rndtrash** [comment]
One note: I actually have made an support letter updater (line 15 in rms-support-letter.sh), so no need to rm -rf it in the Makefile :D
Anyway, neat bash-only solution!

**Comment by tekakutli** [comment]
hello
the github api has bandwith limit
this is the workaround
in this last commit I changed that part of the Makefile, an alternative make clean-all

**Comment by tekakutli** [comment]
with this last commit the cringe label is working for the most part too
do you have a discord?

**Comment by rndtrash** [comment]
Oh I see, sorry, it looks good then :)
Yes, you can find me on RMS Support Letter Discord server (won't tell my username#digits because spambots)

**Pull request merged**
