### PR TITLE
dont actually merge, this is a question

### PR DESCRIPTION
**Pull request by tekakutli**

### CODE REVIEW

**Comment by rndtrash** [comment]
hi fren!
first of all sorry im a little bit dumb and i didnt update the link to css. i dont use tampermonkey anyway :/
secondly to make it work you should remove `@import` and quotation marks, leave just the contents of css, also try to make it one liner by removing new lines
thirdly use database downloader with caution because it might get shell or curl injection etc etc
hope that will help you find more based frens! :)

**Comment by tekakutli** [comment]
very based, thank you

**Comment by rndtrash** [comment]
you're welcome! 👍🏻 
btw if you have a discord account, on RMS supporters' discord `@sowa705` makes based chrome extension that should work better than my userstyle 😉

**Comment by rndtrash** [comment]
Hey fren, i have a little question: WHY IS THERE A LINK TO YOUR GH BOTH ON SUPPORT AND OPEN LETTER?
Снимок экрана от 2021-03-30 21-34-46

**Pull request closed without merging**
